version: '3'

services:
  db:
    image: 'postgres:11.0'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres:
