version: '3'

services:
  db:
    image: 'postgres:11.0'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:7.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  postgres:
  redis:
